service: hrms-system-backend

resources:
  Resources:
    LambdaSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupName: hrms-lambda-sg
        GroupDescription: 'Default Lambda'
        VpcId: vpc-0f0a3d36c7158869c

    LoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Type: application
        Name: msc-app-lb
        Scheme: internal
        Subnets:
          - subnet-08a8f9f0b16b9d40e
          - subnet-0107e88ae4d4afe85
        SecurityGroups:
          - !Ref LambdaSecurityGroup

    LoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref LBTargetGroup
        LoadBalancerArn: !Ref LoadBalancer
        Port: 80
        Protocol: HTTP

    LBTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: LBTargetGroup
        Port: 80
        Protocol: HTTP
        TargetType: lambda
        Targets:
          - Id: !GetAtt UserManagementAPI.Arn
            Port: 80

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

functions:
  UserManagementAPI:
    handler: src/userManagementApi/app.handler
    timeout: 60 # seconds
    memorySize: 128 # mb
    events:
      - alb:
        listenerArn: !Ref LoadBalancerListener
        priority: 1
        condition:
          path:
            - /*
    vpc:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        - subnet-08a8f9f0b16b9d40e
        - subnet-0107e88ae4d4afe85
