service: hr-system-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

functions:
  user-management-api:
    handler: src/userManagementApi/app.handler
    timeout: 60 # seconds
    memorySize: 128 # mb
    events:
      - http: ANY /{proxy+}
      - http: ANY /
       